sudo: false
language: python
python:
  - '2.7'
services:
  - elasticsearch

before_install:
  - pip install --upgrade pip
install:
  - pip install -r requirements-dev.txt
  - pip install coveralls
script:
  - flake8
  - py.test elasticgit -s --cov ./elasticgit
after_success:
  - coveralls
deploy:
  provider: pypi
  user: Praekelt
  password:
    secure: EA5FqGREb4eAPa+lf7/qtAFQW8eCvvQA6RTbnpwvPhYRxvFtudi0v/r668dX08LEwsIlqJ4X02XjMJNBU2rn3VGvsgStJPBnhkf5BptbbiCdVM+T9FhNN2jLMUk4fmFjrniHt/4a/biKgTMDgWek7xhbaI3gBMQkKY1MFhZRnjI=
  on:
    tags: true
    all_branches: true
